### ISSUE TITLE
Holding an item in 1.8.9 makes 2nd skin layer very bright

### ISSUE THREAD

**Issue by ajhfsdh** [tr7zw/3d-Skin-Layers#53] opened 2022-04-19 19:59 UTC
Whenever you hold an item when using the 1.8.9 version of this mod, the 2nd skin layer becomes very bright. This happens on a fresh install of Minecraft 1.8.9 (with forge 2318) without any other mods. I understand that legacy versions most likely aren't high priority, but it would be nice if this were to be fixed.

https://imgur.com/a/UHSJJ45

**Comment by tr7zw** [comment] 2022-04-19 20:36
I did notice the issue, but I had a really had time to reproduce/figure out why that happens. Holding an item might be a really good clue on that one, thanks.

**Comment by ajhfsdh** [comment] 2022-04-20 08:20
Your welcome. Not sure if it helps, but it does not seem to occur with the player model inside of the inventory

**Comment by tr7zw** [comment] 2022-04-20 11:08
Ok was able to reproduce it better thanks to that. Still unable to figure out what kind of opengl 1.8 jank causes this. Instead, I did a logic rework that I wanted to do anyway. This fixed in one big swoop: glowing layers, the red damage tint not looking right, and labymod compatibility 👍.

**Closed** 2022-04-20 11:30 UTC

**Comment by ajhfsdh** [comment] 2022-04-20 20:00
This update has unfortunately broken compatibility with [Orange Marshall's Old Animations Mod](https://www.curseforge.com/minecraft/mc-mods/old-animations-mod) (A mod, which a lot of 1.8.9 players use). If these 2 mods are used together, the 2nd skin layer completely fails to render.

![2022-04-20_21 58 39](https://user-images.githubusercontent.com/97449952/164312895-70c03866-7282-4bb6-b52d-968d4f46d74e.png)

**Comment by tr7zw** [comment] 2022-04-20 20:04
Welp this change fixed everything else(especially labymod), so I think that's more important tbh(since it contains 1.7 animations too). I instead now ported WaveyCapes to 1.8 (basically a free version of Lunar/Badlion cloth capes https://www.curseforge.com/minecraft/mc-mods/waveycapes ).
Also noteworthy to old animations: This project is abandoned and its default file will likely not work with the most recent version of Minecraft. Whether this project is out of date or its author has marked it as abandoned, this project is no longer maintained.

So using something maintained like LabyMod might be a better idea.

**Comment by ajhfsdh** [comment] 2022-04-20 20:50
I completely understand not wanting to support a mod, which is no longer maintained, and supporting mods which are still maintained is of higher priority, however, the mod still works flawlessly and a large number of people still playing 1.8.9 use the mod. Equally, using LabyMod only for old animations seems like overkill.

**Comment by tr7zw** [comment] 2022-04-20 20:52
I mean then for now the "fix" is to use the last release with the broken lighting. Since I haven't gotten it working with old animations and working light at all so far.

**Comment by ajhfsdh** [comment] 2022-04-20 20:54
For now I'll probably just use this mod w/o 1.7 animations, however, if you ever get the motivation to fix compatibility between the two mods, that would be great.

**Comment by tr7zw** [comment] 2022-04-20 20:57
I fixed all the issues by hooking into the player model rendering instead of having the layers in a separate logic like the cape/held item/armor/arrows stuck in the player etc. This auto fixes all the OpenGl setup for lighting, the red tint etc. Since it apparently breaks with OldAnimations, my worst fear is that it replaces the entire EntityModel logic with a core mod or something. Would have no clue how to work around that. Right now I'm bashing my head against 1.12 gradle, trying to get this mod running in there.

**Comment by ajhfsdh** [comment] 2022-04-20 21:05
That seems problematic, as the entire fix, which you just implemented will be completely incompatible with Old Animations Mod.

**Comment by tr7zw** [comment] 2022-04-21 21:27
Like I said, it's no fix and Old Animations or the fixed version and no old animations^^ The correct way is to fix whatever old animations screws up, but it's an old, unmaintained 1.8 mod.
