### ISSUE TITLE
3D Layer parts isn't aligned perfectly with some animations

### ISSUE THREAD

**Issue by NaiNonTH** [tr7zw/3d-Skin-Layers#12] opened 2021-09-30 03:53 UTC
I'll let the images explain you :)

Vanilla Crouching [It is supposed to be black (outer layer) but it's white (the inner layer)] ( Duplicate of #11 )
![2021-09-30_10 47 21](https://user-images.githubusercontent.com/61338902/135384160-fdd30b2e-9856-4d27-8191-bcce1ba61958.png)

Also the climbing animation (with Not Enough Animation)
![2021-09-30_10 47 48](https://user-images.githubusercontent.com/61338902/135384197-558b3b82-a316-4678-8ae1-23db5e372af5.png)
and my arm-part is supposed to be a bit higher

**Comment by tr7zw** [comment] 2021-09-30 12:00
Duplicate of #11

**Closed by tr7zw** 2021-09-30 12:00 UTC
