### ISSUE TITLE
3d-Skin-Layers 'Duplicate Mods'

### ISSUE THREAD

**Issue by Athennnn** [tr7zw/3d-Skin-Layers#112] opened 2023-06-14 08:48 UTC
Don't know what happened, **I only have one version of it in here**. I have a Latest Log ready for you as well.

[latest.log](https://github.com/tr7zw/3d-Skin-Layers/files/11743623/latest.log)

I'll do my best to remember to check in on this, and thank you in advance for the help.
![image_2023-06-14_014818300](https://github.com/tr7zw/3d-Skin-Layers/assets/129617774/a4862714-602d-450d-9c13-f19ae73c6081)
![image_2023-06-14_014833774](https://github.com/tr7zw/3d-Skin-Layers/assets/129617774/c51391ab-43c7-4b86-a795-6879ebd52cab)

**Comment by tr7zw** [comment] 2023-06-15 08:55
Duplicate of #55 . That error is clearly wrong, I suspect it results either from a corrupt jar or due to a conflict with mixinbooter(3d skin layers already contains mixin, potentially a different version).

**Closed by tr7zw** 2023-06-15 08:55 UTC

**Comment by Athennnn** [comment] 2023-06-15 20:59
I downloaded the jar from Curseforge and from modrinth, when I remove mixinbooster it doesn't even let me launch the game and after trying to use it with a fresh install the same problem with 'duplicate mods' appeared again despite being the only mod in the folder.

I'm not the best with MC modding so where would I get an uncorrupted .jar if I've already downloaded it from two different sources.

**Comment by tr7zw** [comment] 2023-06-15 21:00
Pretty sure it's the mixinbooter jar. If another mod needs that, then they are just plain incompatible. 1.12 doesn't really get any support at this point.

**Comment by Athennnn** [comment] 2023-06-15 21:03
Fair, just confused why it wouldn't work with a fresh install. there are... no other mods in here and haven't been any other mods in here. 
![image](https://github.com/tr7zw/3d-Skin-Layers/assets/129617774/08c927ee-35ee-42f3-88a2-e479eaa00198)
